#!bin/bash

echo "Hello i am learning DevOps"
echo "This is my 2nd day of learning git"
echo "I created one more file in git today"
echo "last night i learnt about variables"
echo "I am adding one more file"
echo "before add file to temp area make sure that where u are located or else change directory to particular location"
echo "Thank you"pwd

